import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../public/profile.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blogoo - Tobias' personal blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap" rel="stylesheet"></link>
      </Head>

      <main>
        <div className="profile">
          <div className="profile--pic">
            <Image
              src={profilePic}
              alt="Site icon"
              width={140}
              height={140}
            />
          </div>

          <h1>
            Tobias
          </h1>
        </div>
        <p>
          Hello, my names is <b>Tobias</b>. I am an UX Designer and Front End Developer.
          This is the first thing I’ve developed with Next.js. I am looking forward
          to developing more applications but for now, enjoy this blog! Find more soon on my{" "}
          <a href="https://github.com/Aneksuz" target="_blank">Github</a>
        </p>

        <h2>Blog</h2>

      </main>
      <footer>

      </footer>
    </div>
  )
}
